-- Create Profiles Table (if not exists)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text not null,
  role text not null,
  email text,
  pin text,
  avatar_color text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for Profiles
alter table public.profiles enable row level security;

-- Policies for Profiles (Drop and Recreate to avoid errors)
drop policy if exists "Public profiles are viewable by everyone" on profiles;
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

drop policy if exists "Users can insert their own profile" on profiles;
create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );

drop policy if exists "Users can update own profile" on profiles;
create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Create Chat Messages Table
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid not null, -- can reference profiles(id)
  sender_name text not null,
  sender_avatar text,
  channel_id text default 'global',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for Chat
alter table public.chat_messages enable row level security;

-- Policies for Chat
drop policy if exists "Chat is viewable by everyone" on chat_messages;
create policy "Chat is viewable by everyone"
  on chat_messages for select
  using ( true );

drop policy if exists "Users can insert chat messages" on chat_messages;
create policy "Users can insert chat messages"
  on chat_messages for insert
  with check ( auth.role() = 'authenticated' );
